export const examDates = {
  bac: '2026-06-15',
  grandOral: '2026-06-30',
};

export const navigation = [
  { hash: 'accueil', label: 'Accueil' },
  { hash: 'planning', label: 'Planning' },
  { hash: 'maths', label: 'Maths' },
  { hash: 'physique', label: 'Physique-chimie' },
  { hash: 'sti2d', label: 'STI2D / SIN' },
  { hash: 'sujets-bac', label: 'Sujets bac' },
  { hash: 'priorites', label: 'Priorités' },
  { hash: 'revision-express', label: 'Révision express' },
  { hash: 'erreurs', label: 'Erreurs' },
  { hash: 'grand-oral', label: 'Grand Oral' },
  { hash: 'tests', label: 'Mini-tests' },
  { hash: 'suivi', label: 'Suivi' },
  { hash: 'methode', label: 'Méthode' },
];

export const planning = [
  {
    id: 'semaine-1',
    label: 'Semaine 1 - 18 au 24 mai',
    focus: 'Reprendre les bases et installer une routine simple',
    sessions: [
      {
        id: 's1-lun-maths',
        date: '2026-05-18',
        day: 'Lundi',
        duration: '1h30',
        subject: 'Mathématiques',
        objective: 'Relire les bases de fonctions et de lecture de graphique',
        notion: 'Fonctions, tableaux de valeurs, graphiques',
        task: 'Faire une fiche ultra simple avec vocabulaire, repères et 3 exercices courts.',
        expected: 'Savoir lire une courbe, placer un point et expliquer une variation.',
      },
      {
        id: 's1-mar-pc',
        date: '2026-05-19',
        day: 'Mardi',
        duration: '1h30',
        subject: 'Physique-chimie',
        objective: 'Revoir les grandeurs, unités et conversions de base',
        notion: 'Grandeurs physiques, unités, conversions',
        task: 'Construire un tableau des unités utiles et refaire 5 conversions.',
        expected: 'Ne plus confondre V, A, Ω, W, J et leurs conversions.',
      },
      {
        id: 's1-mer-sti2d',
        date: '2026-05-20',
        day: 'Mercredi',
        duration: '1h00',
        subject: '2I2D / STI2D',
        objective: 'Identifier les chaînes d’information et d’énergie',
        notion: 'Chaînes fonctionnelles',
        task: 'Dessiner un système simple et placer capteur, traitement, actionneur.',
        expected: 'Savoir décrire un système technique en 4 lignes claires.',
      },
      {
        id: 's1-jeu-maths',
        date: '2026-05-21',
        day: 'Jeudi',
        duration: '1h30',
        subject: 'Mathématiques',
        objective: 'Travailler les pourcentages, proportions et puissances',
        notion: 'Proportionnalité et calculs rapides',
        task: 'Faire 10 calculs courts puis corriger les erreurs sans regarder la correction.',
        expected: 'Gagner en vitesse sur les calculs de base.',
      },
      {
        id: 's1-ven-rattrapage',
        date: '2026-05-22',
        day: 'Vendredi',
        duration: '45 min',
        subject: 'Rattrapage',
        objective: 'Rattraper la séance ratée ou refaire une erreur importante',
        notion: 'Rattrapage ciblé',
        task: 'Reprendre uniquement l’erreur la plus fréquente de la semaine.',
        expected: 'Corriger un point faible précis au lieu de tout refaire.',
      },
      {
        id: 's1-sam-pc',
        date: '2026-05-23',
        day: 'Samedi',
        duration: '2h00',
        subject: 'Physique-chimie',
        objective: 'Revoir tension, intensité, résistance et loi d’Ohm',
        notion: 'Électricité de base',
        task: 'Faire un mini-exercice complet avec calculs, unités et phrase de conclusion.',
        expected: 'Savoir utiliser U = R × I correctement.',
      },
      {
        id: 's1-dim-léger',
        date: '2026-05-24',
        day: 'Dimanche',
        duration: '45 min',
        subject: 'Léger',
        objective: 'Faire une demi-journée légère',
        notion: 'Relecture',
        task: 'Relire les fiches et surligner 5 points à revoir la semaine suivante.',
        expected: 'Finir la semaine sans surcharge.',
      },
    ],
  },
  {
    id: 'semaine-2',
    label: 'Semaine 2 - 25 au 31 mai',
    focus: 'Sécuriser les chapitres les plus rentables pour le bac',
    sessions: [
      {
        id: 's2-lun-maths',
        date: '2026-05-25',
        day: 'Lundi',
        duration: '1h30',
        subject: 'Mathématiques',
        objective: 'Revoir la dérivation et le lien avec les variations',
        notion: 'Dérivation',
        task: 'Faire un tableau de signes puis expliquer le sens de variation de la fonction.',
        expected: 'Relier dérivée, signe et variation sans bloquer.',
      },
      {
        id: 's2-mar-pc',
        date: '2026-05-26',
        day: 'Mardi',
        duration: '1h30',
        subject: 'Physique-chimie',
        objective: 'Travailler énergie, puissance et rendement',
        notion: 'Énergie et rendement',
        task: 'Résoudre 3 situations techniques courtes avec formule et unités.',
        expected: 'Choisir la bonne formule et vérifier l’ordre de grandeur.',
      },
      {
        id: 's2-mer-sti2d',
        date: '2026-05-27',
        day: 'Mercredi',
        duration: '1h00',
        subject: '2I2D / STI2D',
        objective: 'Comprendre capteurs, actionneurs et systèmes embarqués',
        notion: 'Composants d’un système',
        task: 'Associer chaque composant à son rôle dans un exemple SIN concret.',
        expected: 'Expliquer un système embarqué avec des mots simples.',
      },
      {
        id: 's2-jeu-maths',
        date: '2026-05-28',
        day: 'Jeudi',
        duration: '1h30',
        subject: 'Mathématiques',
        objective: 'Revoir suites et lecture de données techniques',
        notion: 'Suites et données',
        task: 'Faire 2 suites et 1 tableau de données à commenter.',
        expected: 'Savoir décrire une évolution et repérer une tendance.',
      },
      {
        id: 's2-ven-rattrapage',
        date: '2026-05-29',
        day: 'Vendredi',
        duration: '45 min',
        subject: 'Rattrapage',
        objective: 'Refaire une séance en difficulté',
        notion: 'Correction active',
        task: 'Reprendre la correction d’un exercice raté et écrire la méthode.',
        expected: 'Transformer une erreur en méthode claire.',
      },
      {
        id: 's2-sam-pc',
        date: '2026-05-30',
        day: 'Samedi',
        duration: '2h15',
        subject: 'Physique-chimie',
        objective: 'Maîtriser le courant, la tension, la résistance et les graphiques',
        notion: 'Mesures et graphique',
        task: 'Lire un graphique expérimental puis rédiger une réponse complète.',
        expected: 'Savoir décrire une mesure et conclure avec précision.',
      },
      {
        id: 's2-dim-léger',
        date: '2026-05-31',
        day: 'Dimanche',
        duration: '45 min',
        subject: 'Léger',
        objective: 'Faire le point sur les acquis',
        notion: 'Auto-évaluation',
        task: 'Coche ce qui est acquis et note les 3 points faibles à revoir.',
        expected: 'Préparer la semaine suivante sans stress.',
      },
    ],
  },
  {
    id: 'semaine-3',
    label: 'Semaine 3 - 1er au 7 juin',
    focus: 'Passer du cours à l’exercice type bac',
    sessions: [
      {
        id: 's3-lun-maths',
        date: '2026-06-01',
        day: 'Lundi',
        duration: '1h30',
        subject: 'Mathématiques',
        objective: 'Travailler les probabilités et statistiques',
        notion: 'Probabilités / statistiques',
        task: 'Faire un exercice de lecture de tableau puis une question de probabilité simple.',
        expected: 'Réussir les bases de lecture et de calcul.',
      },
      {
        id: 's3-mar-pc',
        date: '2026-06-02',
        day: 'Mardi',
        duration: '1h30',
        subject: 'Physique-chimie',
        objective: 'Revoir les chaînes d’énergie et les conversions d’unités',
        notion: 'Chaînes d’énergie',
        task: 'Annoter un schéma puis refaire toutes les conversions sans erreur.',
        expected: 'Savoir relier chaque bloc à son rôle technique.',
      },
      {
        id: 's3-mer-sti2d',
        date: '2026-06-03',
        day: 'Mercredi',
        duration: '1h00',
        subject: '2I2D / STI2D',
        objective: 'Revoir analyse fonctionnelle et contraintes techniques',
        notion: 'Fonctions et contraintes',
        task: 'Identifier la fonction d’usage et les contraintes sur un système SIN.',
        expected: 'Exprimer un besoin technique clairement.',
      },
      {
        id: 's3-jeu-maths',
        date: '2026-06-04',
        day: 'Jeudi',
        duration: '1h30',
        subject: 'Mathématiques',
        objective: 'Faire une séance complète type bac courte',
        notion: 'Exercice mixte',
        task: 'Enchaîner calculs, équation simple et lecture de graphique en temps limité.',
        expected: 'Gagner en autonomie et en méthode.',
      },
      {
        id: 's3-ven-rattrapage',
        date: '2026-06-05',
        day: 'Vendredi',
        duration: '45 min',
        subject: 'Rattrapage',
        objective: 'Réparer le point le plus fragile',
        notion: 'Rattrapage ciblé',
        task: 'Reprendre un chapitre raté sans te disperser.',
        expected: 'Réduire la charge mentale avant le week-end.',
      },
      {
        id: 's3-sam-pc',
        date: '2026-06-06',
        day: 'Samedi',
        duration: '2h15',
        subject: 'Physique-chimie',
        objective: 'Faire un sujet court avec calculs et rédaction',
        notion: 'Méthode bac',
        task: 'Rédiger comme au bac: données, formule, calcul, conclusion.',
        expected: 'Produire une réponse propre et lisible.',
      },
      {
        id: 's3-dim-léger',
        date: '2026-06-07',
        day: 'Dimanche',
        duration: '45 min',
        subject: 'Léger',
        objective: 'Revoir les fiches sans se fatiguer',
        notion: 'Lecture active',
        task: 'Relire 3 fiches et réciter les formules à voix haute.',
        expected: 'Consolider sans surcharge.',
      },
    ],
  },
  {
    id: 'semaine-4',
    label: 'Semaine 4 - 8 au 14 juin',
    focus: 'Révisions finales, consolidation et gestion du stress',
    sessions: [
      {
        id: 's4-lun-maths',
        date: '2026-06-08',
        day: 'Lundi',
        duration: '1h30',
        subject: 'Mathématiques',
        objective: 'Réviser les calculs de base, pourcentages et puissances',
        notion: 'Automatismes',
        task: 'Faire un entraînement chronométré avec correction immédiate.',
        expected: 'Répondre vite aux questions faciles.',
      },
      {
        id: 's4-mar-pc',
        date: '2026-06-09',
        day: 'Mardi',
        duration: '1h30',
        subject: 'Physique-chimie',
        objective: 'Réviser énergie, rendement et loi d’Ohm',
        notion: 'Formules prioritaires',
        task: 'Refaire 3 exercices où chaque donnée est bien identifiée.',
        expected: 'Ne plus hésiter sur les formules de base.',
      },
      {
        id: 's4-mer-sti2d',
        date: '2026-06-10',
        day: 'Mercredi',
        duration: '1h00',
        subject: '2I2D / STI2D',
        objective: 'Revoir le vocabulaire technique de SIN',
        notion: 'Vocabulaire et systèmes',
        task: 'Faire une carte mentale d’un système connecté de bout en bout.',
        expected: 'Expliquer un projet SIN avec confiance.',
      },
      {
        id: 's4-jeu-mini-test',
        date: '2026-06-11',
        day: 'Jeudi',
        duration: '1h15',
        subject: 'Mini-test',
        objective: 'S’entraîner dans les conditions du bac',
        notion: 'Test blanc court',
        task: 'Faire un mini-test, corriger et noter les erreurs récurrentes.',
        expected: 'Repérer ce qui doit encore être revu avant le 15 juin.',
      },
      {
        id: 's4-ven-rattrapage',
        date: '2026-06-12',
        day: 'Vendredi',
        duration: '45 min',
        subject: 'Rattrapage',
        objective: 'Rattraper une erreur du mini-test',
        notion: 'Correction ciblée',
        task: 'Refaire uniquement les questions ratées.',
        expected: 'Transformer le test en progrès concret.',
      },
      {
        id: 's4-sam-recap',
        date: '2026-06-13',
        day: 'Samedi',
        duration: '2h00',
        subject: 'Révision générale',
        objective: 'Revoir les 3 matières prioritaires',
        notion: 'Synthèse',
        task: 'Passer sur les fiches, les erreurs et les points encore flous.',
        expected: 'Avoir une vision claire de ce qui est acquis.',
      },
      {
        id: 's4-dim-léger',
        date: '2026-06-14',
        day: 'Dimanche',
        duration: '30 min',
        subject: 'Léger',
        objective: 'Préparer le jour J sans se fatiguer',
        notion: 'Veille d’examen',
        task: 'Relire les fiches essentielles, préparer le matériel et dormir tôt.',
        expected: 'Arriver serein le 15 juin.',
      },
    ],
  },
];

export const maths = [
  {
    id: 'maths-fonctions',
    title: 'Fonctions',
    summary: 'Une fonction associe une valeur d’entrée à une valeur de sortie. Il faut savoir lire, calculer et décrire son évolution.',
    example: 'Si f(x) = 2x + 3, alors f(4) = 11. On remplace simplement x par 4.',
    exercise: 'Calculer f(0), f(2) et f(-1) pour f(x) = 3x - 2, puis dire si la fonction augmente ou diminue.',
    errors: ['Oublier de remplacer toute la variable', 'Confondre f(x) et x', 'Ne pas vérifier les unités ou le contexte'],
    checklist: ['Je sais calculer une image', 'Je sais lire un tableau de valeurs', 'Je sais commenter une courbe', 'Je sais repérer une variation'],
  },
  {
    id: 'maths-derivation',
    title: 'Dérivation',
    summary: 'La dérivée sert surtout à étudier les variations d’une fonction et à repérer les extremums.',
    example: 'Si f(x) = x^2, alors f\'(x) = 2x. La dérivée est négative avant 0 et positive après 0.',
    exercise: 'Étudier le signe de la dérivée d’une fonction simple et en déduire un maximum ou un minimum.',
    errors: ['Oublier le lien signe/variation', 'Faire un tableau sans conclure', 'Confondre dérivée et fonction'],
    checklist: ['Je sais calculer une dérivée simple', 'Je sais faire un tableau de signes', 'Je sais conclure sur les variations', 'Je sais lire un extremum'],
  },
  {
    id: 'maths-suites',
    title: 'Suites',
    summary: 'Une suite est une suite de nombres ordonnés. Il faut comprendre son évolution et savoir calculer quelques termes.',
    example: 'Si u0 = 2 et u(n+1) = u(n) + 3, alors u1 = 5, u2 = 8, u3 = 11.',
    exercise: 'Calculer les 4 premiers termes d’une suite définie par récurrence puis décrire son évolution.',
    errors: ['Se tromper de terme de départ', 'Oublier de remplacer le terme précédent', 'Faire des calculs trop vite'],
    checklist: ['Je sais calculer plusieurs termes', 'Je sais repérer une croissance', 'Je sais utiliser une formule de récurrence', 'Je sais lire un terme dans un tableau'],
  },
  {
    id: 'maths-probas',
    title: 'Probabilités et statistiques',
    summary: 'On travaille des fréquences, des moyennes, des pourcentages et des situations simples d’aléatoire.',
    example: 'Si 12 élèves sur 30 réussissent, la fréquence est 12/30 = 0,4 soit 40 %.',
    exercise: 'Calculer une moyenne simple puis une probabilité à partir d’un tableau.',
    errors: ['Confondre fréquence et probabilité', 'Oublier les pourcentages', 'Mal lire un tableau'],
    checklist: ['Je sais calculer une moyenne', 'Je sais lire un tableau de données', 'Je sais calculer une fréquence', 'Je sais interpréter un résultat'],
  },
  {
    id: 'maths-calculs-base',
    title: 'Calculs de base',
    summary: 'Les automatismes doivent être rapides: fractions, décimaux, priorités opératoires, puissances et calcul mental simple.',
    example: '2 + 3 × 4 = 14, car on fait d’abord la multiplication.',
    exercise: 'Refaire 10 calculs en respectant les priorités et écrire le résultat proprement.',
    errors: ['Ignorer les parenthèses', 'Faire les opérations dans le mauvais ordre', 'Oublier les signes'],
    checklist: ['Je respecte les priorités', 'Je connais les puissances de base', 'Je calcule sans me bloquer', 'Je vérifie mes résultats'],
  },
  {
    id: 'maths-graphiques',
    title: 'Lecture de graphiques',
    summary: 'Il faut lire les axes, les unités, les points importants et savoir commenter une tendance.',
    example: 'Sur un graphique temps/température, on lit l’échelle avant de donner une valeur.',
    exercise: 'Décrire un graphique en 5 phrases: axes, tendance, valeur lue, variation, conclusion.',
    errors: ['Lire trop vite sans regarder l’échelle', 'Oublier les unités', 'Confondre courbe et axe'],
    checklist: ['Je lis correctement les axes', 'Je donne une valeur avec unité', 'Je repère une tendance', 'Je formule une conclusion'],
  },
  {
    id: 'maths-proportionnalite',
    title: 'Proportionnalité, pourcentages, puissances',
    summary: 'Ces outils servent tout le temps dans les problèmes techniques, les conversions et les estimations.',
    example: '20 % de 150 = 0,2 × 150 = 30.',
    exercise: 'Calculer une hausse de 12 %, une baisse de 15 % et une puissance de 10.',
    errors: ['Oublier de convertir le pourcentage en nombre décimal', 'Se tromper de sens dans une hausse ou baisse', 'Confondre 10^3 et 10-3'],
    checklist: ['Je calcule un pourcentage', 'Je sais faire une règle de trois simple', 'Je maîtrise les puissances de 10', 'Je sais estimer un ordre de grandeur'],
  },
  {
    id: 'maths-equations',
    title: 'Équations simples',
    summary: 'Il faut savoir résoudre une équation du premier degré étape par étape sans se perdre.',
    example: '2x + 5 = 13 donne 2x = 8 puis x = 4.',
    exercise: 'Résoudre trois équations simples puis vérifier le résultat en remplaçant la valeur trouvée.',
    errors: ['Changer un terme de côté sans changer le signe', 'Aller trop vite dans les étapes', 'Ne pas vérifier la solution'],
    checklist: ['Je isole l’inconnue', 'Je garde une écriture claire', 'Je vérifie ma réponse', 'Je sais expliquer mes étapes'],
  },
  {
    id: 'maths-donnees-techniques',
    title: 'Exploitation de données techniques',
    summary: 'On te demande souvent d’utiliser un tableau, une courbe ou des mesures issues d’un système réel.',
    example: 'À partir d’un relevé de tension, on repère la valeur la plus stable et la plus utile pour conclure.',
    exercise: 'Lire des données techniques et écrire une conclusion en 3 lignes avec valeur, unité et interprétation.',
    errors: ['Recopier sans interpréter', 'Oublier les unités', 'Ne pas relier les données au problème posé'],
    checklist: ['Je lis des données brutes', 'Je relie les chiffres au contexte', 'Je conclus simplement', 'Je justifie avec une mesure'],
  },
];

export const physiqueChimie = [
  {
    id: 'pc-grandeurs',
    title: 'Grandeurs physiques et unités',
    summary: 'Une grandeur se mesure avec une unité. Il faut savoir identifier la grandeur, l’unité et l’instrument.',
    formula: 'Exemple de base: longueur en m, masse en kg, temps en s, tension en V.',
    example: 'Une tension de 12 V ne s’écrit pas 12 sans unité dans une copie scientifique.',
    exercise: 'Associer 10 grandeurs à leurs unités et à l’instrument de mesure.',
    errors: ['Oublier les unités', 'Confondre grandeur et valeur', 'Mettre une mauvaise notation'],
    checklist: ['Je sais nommer une grandeur', 'Je donne l’unité correcte', 'Je choisis l’instrument adapté', 'Je rédige avec précision'],
  },
  {
    id: 'pc-conversions',
    title: 'Conversions d’unités',
    summary: 'Les conversions sont indispensables pour éviter les erreurs de puissance de 10 et de lecture des données.',
    formula: '1 k = 10^3, 1 m = 10^-3, 1 M = 10^6.',
    example: '2,5 kW = 2500 W.',
    exercise: 'Convertir des valeurs de kW, mA, kΩ, MJ et mm en unités de base.',
    errors: ['Confondre milli et mega', 'Multiplier dans le mauvais sens', 'Oublier la cohérence de l’unité finale'],
    checklist: ['Je sais convertir vers l’unité de base', 'Je repère les préfixes', 'Je contrôle l’ordre de grandeur', 'Je vérifie le résultat final'],
  },
  {
    id: 'pc-energie',
    title: 'Énergie',
    summary: 'L’énergie est une quantité utilisée ou transférée dans un système technique.',
    formula: 'E = P × t',
    example: 'Une lampe de 20 W utilisée pendant 2 h consomme E = 20 × 2 = 40 Wh.',
    exercise: 'Calculer l’énergie consommée par un appareil sur une durée donnée.',
    errors: ['Oublier de convertir les heures en secondes quand c’est demandé', 'Confondre énergie et puissance', 'Ne pas donner l’unité'],
    checklist: ['Je sais utiliser E = P × t', 'Je distingue énergie et puissance', 'Je donne une réponse avec unité', 'Je sais estimer une consommation'],
  },
  {
    id: 'pc-puissance',
    title: 'Puissance',
    summary: 'La puissance traduit la rapidité de transfert d’énergie ou de travail.',
    formula: 'P = E / t',
    example: 'Si 600 J sont fournis en 30 s, alors P = 20 W.',
    exercise: 'Calculer une puissance à partir d’une énergie et d’un temps.',
    errors: ['Inverser la formule', 'Confondre J et W', 'Oublier la durée'],
    checklist: ['Je sais calculer une puissance', 'Je comprends la signification physique', 'Je relie puissance et temps', 'Je sais comparer deux systèmes'],
  },
  {
    id: 'pc-rendement',
    title: 'Rendement',
    summary: 'Le rendement compare ce qui est utile à ce qui est fourni. Il sert à évaluer l’efficacité d’un système.',
    formula: 'η = E utile / E reçue',
    example: 'Un système qui fournit 80 J utiles pour 100 J reçus a un rendement de 0,8 soit 80 %.',
    exercise: 'Calculer un rendement puis interpréter s’il est bon ou faible.',
    errors: ['Confondre pourcentage et valeur décimale', 'Mettre le mauvais numérateur', 'Oublier l’interprétation'],
    checklist: ['Je sais calculer un rendement', 'Je sais le convertir en pourcentage', 'Je sais l’interpréter', 'Je sais le comparer'],
  },
  {
    id: 'pc-electricite',
    title: 'Électricité',
    summary: 'Il faut lire un circuit, identifier les grandeurs et comprendre le lien entre tension, courant et résistance.',
    formula: 'U, I, R sont les grandeurs de base d’un circuit.',
    example: 'Dans un montage simple, on mesure la tension aux bornes d’un composant et l’intensité dans la branche.',
    exercise: 'Dessiner un circuit simple et placer les appareils de mesure au bon endroit.',
    errors: ['Placer l’ampèremètre en dérivation', 'Oublier le sens du courant conventionnel', 'Ne pas nommer les branches'],
    checklist: ['Je sais lire un schéma simple', 'Je sais placer les appareils de mesure', 'Je comprends le rôle d’un dipôle', 'Je sais écrire une phrase de conclusion'],
  },
  {
    id: 'pc-circuits',
    title: 'Circuits série et dérivation',
    summary: 'Savoir reconnaître un montage en série ou en dérivation aide à comprendre les mesures et les comportements du circuit.',
    formula: 'En série, l’intensité est la même; en dérivation, la tension est la même.',
    example: 'Deux lampes en dérivation peuvent continuer à fonctionner si l’une est débranchée.',
    exercise: 'Identifier le type de montage sur un schéma et expliquer ce qui change pour le courant et la tension.',
    errors: ['Confondre série et dérivation', 'Appliquer la même règle partout', 'Ne pas relier le schéma à une conséquence concrète'],
    checklist: ['Je reconnais un circuit en série', 'Je reconnais un circuit en dérivation', 'Je sais dire ce qui se conserve', 'Je sais interpréter une panne simple'],
  },
  {
    id: 'pc-ohm',
    title: 'Loi d’Ohm',
    summary: 'La loi d’Ohm relie tension, intensité et résistance dans un dipôle ohmique.',
    formula: 'U = R × I',
    example: 'Avec R = 10 Ω et I = 0,5 A, on obtient U = 5 V.',
    exercise: 'Calculer la grandeur manquante dans 3 situations différentes.',
    errors: ['Oublier de transformer mA en A', 'Inversement, confondre U = I × R et U = R / I', 'Ne pas vérifier les unités'],
    checklist: ['Je sais utiliser U = R × I', 'Je convertis les unités avant de calculer', 'Je sais isoler la bonne grandeur', 'Je vérifie le sens du résultat'],
  },
  {
    id: 'pc-puissance-electrique',
    title: 'Puissance électrique',
    summary: 'La puissance électrique est essentielle pour relier les appareils, la consommation et le dimensionnement d’une solution.',
    formula: 'P = U × I',
    example: 'Avec U = 12 V et I = 2 A, on obtient P = 24 W.',
    exercise: 'Calculer la puissance électrique d’un composant puis l’énergie consommée sur une durée donnée.',
    errors: ['Confondre puissance et énergie', 'Oublier de convertir les unités', 'Utiliser une formule au hasard'],
    checklist: ['Je sais utiliser P = U × I', 'Je distingue puissance et énergie', 'Je sais relier la puissance à la consommation', 'Je sais vérifier un ordre de grandeur'],
  },
  {
    id: 'pc-chaines-energie',
    title: 'Chaînes d’énergie',
    summary: 'Une chaîne d’énergie décrit comment l’énergie est alimentée, distribuée, convertie et transmise.',
    formula: 'Pas de formule unique, il faut comprendre le rôle de chaque bloc.',
    example: 'Batterie -> distribution -> moteur -> mouvement.',
    exercise: 'Compléter une chaîne d’énergie à partir d’un système technique réel.',
    errors: ['Confondre chaîne d’énergie et chaîne d’information', 'Oublier un bloc', 'Ne pas relier le schéma au système'],
    checklist: ['Je sais nommer les blocs', 'Je sais décrire le trajet de l’énergie', 'Je sais relier le schéma au système', 'Je sais conclure sur le rendement'],
  },
  {
    id: 'pc-solutions',
    title: 'Solutions, concentration et dilution',
    summary: 'Cette base de chimie suffit souvent pour les exercices simples: lire un dosage, une solution et une dilution.',
    formula: 'c = m / V',
    example: 'Si 5 g de soluté sont dissous dans 0,5 L, alors c = 10 g/L.',
    exercise: 'Calculer une concentration simple ou retrouver la masse de soluté à partir d’un volume donné.',
    errors: ['Confondre masse et volume', 'Oublier l’unité', 'Ne pas faire attention au litre ou au mL'],
    checklist: ['Je sais lire une concentration', 'Je sais utiliser une formule simple', 'Je convertis les volumes correctement', 'Je sais interpréter une solution'],
  },
  {
    id: 'pc-ordres-grandeur',
    title: 'Ordres de grandeur',
    summary: 'Un ordre de grandeur sert à vérifier si un résultat est plausible.',
    formula: 'On compare souvent une valeur à 10^n ou à une estimation de référence.',
    example: 'Une puissance de 1 MW n’a pas du tout le même sens qu’une puissance de 1 W.',
    exercise: 'Dire si un résultat est réaliste ou incohérent à partir d’un contexte simple.',
    errors: ['Accepter un résultat absurde', 'Ne pas comparer à une référence', 'Confondre grande et petite puissance'],
    checklist: ['Je vérifie la cohérence', 'Je sais estimer rapidement', 'Je repère une erreur de puissance de 10', 'Je conclus avec prudence'],
  },
  {
    id: 'pc-graphiques',
    title: 'Graphiques et mesures',
    summary: 'Il faut lire, exploiter et commenter un graphique expérimental avec méthode.',
    formula: 'Aucune formule unique, mais la rigueur des unités est indispensable.',
    example: 'Un nuage de points peut montrer une relation quasi linéaire entre deux grandeurs.',
    exercise: 'Décrire un graphique, citer une valeur lue et formuler une conclusion scientifique simple.',
    errors: ['Oublier l’échelle', 'Recopier sans interpréter', 'Ne pas écrire les unités'],
    checklist: ['Je lis un graphique', 'Je distingue mesure et interprétation', 'Je cite des valeurs précises', 'Je conclus avec une phrase claire'],
  },
  {
    id: 'pc-mesures',
    title: 'Mesures et qualité du résultat',
    summary: 'Savoir commenter une mesure, sa précision et sa cohérence permet de gagner des points dans les réponses rédigées.',
    formula: 'Résultat = valeur + unité, avec une vérification de cohérence.',
    example: 'Si une valeur calculée est 0,002 W alors il faut vérifier si le résultat est crédible dans le contexte.',
    exercise: 'Relire une mesure et dire si elle est plausible, bien écrite et exploitable.',
    errors: ['Écrire une valeur sans unité', 'Ne pas commenter la cohérence', 'Ignorer l’arrondi ou la précision'],
    checklist: ['Je donne une valeur avec unité', 'Je vérifie la cohérence', 'Je sais commenter un résultat', 'Je sais repérer une mesure aberrante'],
  },
];

export const sti2d = [
  {
    id: 'sti2d-chaines-info',
    title: 'Chaîne d’information',
    summary: 'La chaîne d’information capte, traite et transmet les informations utiles au système.',
    example: 'Un capteur détecte une présence, la carte électronique traite le signal puis déclenche une alerte.',
    diagram: ['Entrée capteur -> acquisition -> traitement -> commande'],
    exercise: 'Placer les bonnes fonctions sur un schéma de système connecté.',
    checklist: ['Je sais identifier la fonction capteur', 'Je sais repérer le traitement', 'Je sais expliquer la commande', 'Je sais relier le schéma au besoin'],
  },
  {
    id: 'sti2d-chaines-energie',
    title: 'Chaîne d’énergie',
    summary: 'La chaîne d’énergie alimente, distribue, convertit et transmet l’énergie.',
    example: 'Un drone reçoit l’énergie de la batterie, la distribue et la transforme en mouvement par les moteurs.',
    diagram: ['Source -> distribution -> conversion -> transmission'],
    exercise: 'Compléter un schéma d’énergie sur un objet technique simple.',
    checklist: ['Je distingue énergie et information', 'Je sais nommer les blocs', 'Je repère la conversion', 'Je sais expliquer le trajet de l’énergie'],
  },
  {
    id: 'sti2d-capteurs',
    title: 'Capteurs',
    summary: 'Un capteur transforme une grandeur physique en information exploitable.',
    example: 'Un capteur de température renvoie une valeur qui peut être lue par le système.',
    diagram: ['Température, lumière, position, distance, courant'],
    exercise: 'Associer chaque capteur à la grandeur mesurée.',
    checklist: ['Je sais ce qu’un capteur mesure', 'Je sais lire une valeur', 'Je sais expliquer son intérêt', 'Je sais le placer dans une chaîne d’information'],
  },
  {
    id: 'sti2d-actionneurs',
    title: 'Actionneurs',
    summary: 'Un actionneur transforme une commande en action physique concrète.',
    example: 'Un moteur, une LED, un relais ou un servo-moteur sont des actionneurs courants.',
    diagram: ['Commande -> actionneur -> action'],
    exercise: 'Choisir l’actionneur adapté à une situation donnée.',
    checklist: ['Je sais définir un actionneur', 'Je connais des exemples', 'Je sais relier la commande à l’action', 'Je sais expliquer le résultat obtenu'],
  },
  {
    id: 'sti2d-systemes-embarques',
    title: 'Systèmes embarqués',
    summary: 'Un système embarqué est intégré dans un objet et fonctionne avec des contraintes de taille, d’énergie et de fiabilité.',
    example: 'Une carte électronique dans un drone pilote les moteurs et récupère les capteurs.',
    diagram: ['Capteurs + microcontrôleur + énergie + communication'],
    exercise: 'Décrire un système embarqué en citant ses contraintes techniques.',
    checklist: ['Je sais définir un système embarqué', 'Je connais ses contraintes', 'Je sais parler d’autonomie', 'Je sais donner un exemple SIN'],
  },
  {
    id: 'sti2d-reseaux',
    title: 'Réseaux',
    summary: 'Les réseaux permettent d’échanger des données entre systèmes ou entre modules.',
    example: 'Une infrastructure numérique autonome doit parfois transporter des données localement sans dépendre d’un grand réseau.',
    diagram: ['Terminal -> routeur -> réseau local -> service'],
    exercise: 'Citer un intérêt et une limite d’un réseau dans un projet technique.',
    checklist: ['Je sais expliquer un réseau local', 'Je comprends le besoin de communication', 'Je connais une limite de débit ou de portée', 'Je sais faire le lien avec le projet'],
  },
  {
    id: 'sti2d-autonomie-energetique',
    title: 'Autonomie énergétique',
    summary: 'On cherche à faire fonctionner un système avec une énergie disponible et maîtrisée.',
    example: 'Un système solaire doit stocker ou consommer l’énergie au bon moment.',
    diagram: ['Production -> stockage -> consommation'],
    exercise: 'Proposer une solution simple pour améliorer l’autonomie d’un système.',
    checklist: ['Je sais parler de stockage', 'Je comprends les limites d’énergie', 'Je sais estimer une consommation', 'Je sais proposer une amélioration'],
  },
  {
    id: 'sti2d-contraintes',
    title: 'Contraintes techniques',
    summary: 'Un cahier des charges impose des contraintes de coût, sécurité, performance, taille et délai.',
    example: 'Un drone de recherche doit être léger, autonome, fiable et simple à piloter.',
    diagram: ['Coût, poids, énergie, sécurité, usage'],
    exercise: 'Classer des contraintes en contraintes fortes et contraintes de confort.',
    checklist: ['Je sais identifier une contrainte', 'Je sais la justifier', 'Je sais la prioriser', 'Je sais parler d’arbitrage'],
  },
  {
    id: 'sti2d-dd',
    title: 'Développement durable',
    summary: 'Un projet technique doit prendre en compte l’environnement, la société et l’économie.',
    example: 'Choisir un composant durable peut réduire les déchets et la maintenance.',
    diagram: ['Environnement + social + économique'],
    exercise: 'Expliquer en 3 phrases pourquoi une solution est plus durable qu’une autre.',
    checklist: ['Je sais citer les 3 piliers', 'Je sais parler d’impact environnemental', 'Je sais relier au besoin social', 'Je sais faire une conclusion critique'],
  },
  {
    id: 'sti2d-cycle-vie',
    title: 'Cycle de vie',
    summary: 'Le cycle de vie analyse la matière première, la fabrication, l’usage et la fin de vie.',
    example: 'Un objet recyclable ou réparable a souvent un meilleur profil environnemental.',
    diagram: ['Conception -> fabrication -> usage -> recyclage'],
    exercise: 'Relier une amélioration produit à une étape du cycle de vie.',
    checklist: ['Je sais décrire le cycle de vie', 'Je sais parler de recyclage', 'Je sais parler de réparation', 'Je sais relier le cycle au développement durable'],
  },
  {
    id: 'sti2d-analyse-fonctionnelle',
    title: 'Analyse fonctionnelle',
    summary: 'L’analyse fonctionnelle cherche à définir le besoin, la fonction d’usage et les fonctions techniques.',
    example: 'Un système de drone doit localiser, détecter et transmettre une alerte.',
    diagram: ['Besoin -> fonction d’usage -> fonctions techniques'],
    exercise: 'Écrire la fonction d’usage d’un système en une phrase.',
    checklist: ['Je sais définir le besoin', 'Je sais formuler une fonction d’usage', 'Je sais distinguer fonction et solution', 'Je sais relier au projet'],
  },
  {
    id: 'sti2d-sysml',
    title: 'Diagrammes SysML',
    summary: 'Les diagrammes SysML servent à décrire un système technique de manière lisible et structurée.',
    example: 'Un diagramme peut montrer les blocs, les interactions et les contraintes principales.',
    diagram: ['Bloc système -> sous-systèmes -> relations'],
    exercise: 'Lire un diagramme simple et retrouver le rôle de chaque bloc.',
    checklist: ['Je reconnais un diagramme SysML simple', 'Je lis les blocs', 'Je comprends les relations', 'Je sais expliquer le rôle de chaque sous-système'],
  },
  {
    id: 'sti2d-architecture',
    title: 'Architecture d’un système technique',
    summary: 'L’architecture relie tous les éléments du système: information, énergie, communication et usage.',
    example: 'Une solution SIN combine capteurs, traitement, communication et action.',
    diagram: ['Capteurs -> carte -> réseau -> utilisateur'],
    exercise: 'Dessiner l’architecture d’un système technique simple.',
    checklist: ['Je sais lister les blocs d’un système', 'Je sais relier les blocs', 'Je sais expliquer l’ensemble', 'Je sais rester clair et simple'],
  },
  {
    id: 'sti2d-sin',
    title: 'Notions clés SIN',
    summary: 'La spécialité SIN met l’accent sur l’information, la programmation, les réseaux et l’intégration d’un système connecté.',
    example: 'Un service de suivi à distance peut combiner interface, communication et collecte de données.',
    diagram: ['Interface -> données -> réseau -> décision'],
    exercise: 'Présenter un projet SIN en 4 idées simples.',
    checklist: ['Je sais parler de données', 'Je sais parler de réseau', 'Je sais parler de programmation', 'Je sais faire le lien avec un besoin réel'],
  },
];

export const grandOral = [
  {
    id: 'or-madagascar',
    title: 'Le dimensionnement d’une infrastructure numérique autonome à Madagascar',
    problem: 'Comment dimensionner une infrastructure numérique autonome capable de fonctionner dans des zones où l’accès à l’énergie et au réseau est limité ?',
    intro: 'Ce sujet permet de relier les besoins réels d’un territoire, l’autonomie énergétique, les réseaux locaux et les choix techniques d’un projet SIN.',
    plan: [
      '1. Identifier le besoin réel: connexion, service local, stockage, fiabilité.',
      '2. Dimensionner la solution: énergie, réseau, sécurité, matériel et autonomie.',
      '3. Vérifier la pertinence: coût, maintenance, impact environnemental et usage social.',
    ],
    sti2d: ['Autonomie énergétique', 'Réseaux', 'Architecture système', 'Contraintes techniques'],
    sciences: ['Puissance', 'Énergie', 'Ordres de grandeur', 'Conversions d’unités'],
    impacts: [
      'Développement durable: limiter la consommation et favoriser la maintenance simple.',
      'Société: aider l’accès à l’information, à l’éducation ou à des services utiles.',
      'Contraintes réelles: climat, distance, coût, maintenance et disponibilité des composants.',
    ],
    conclusion: 'Le bon dimensionnement consiste à trouver un compromis entre autonomie, fiabilité et simplicité de maintenance.',
    opening: 'On peut ouvrir sur d’autres zones isolées où une solution autonome améliore la continuité des services essentiels.',
    memo: [
      'Parler d’abord du besoin, pas de la technologie.',
      'Toujours justifier avec une contrainte concrète.',
      'Donner au moins un exemple d’énergie et un exemple de réseau.',
      'Terminer par le compromis technique.',
    ],
    twoMinutes: 'Je vais montrer comment dimensionner une infrastructure numérique autonome pour répondre à un besoin réel à Madagascar. L’enjeu est d’assurer un service utile malgré des contraintes d’énergie, de réseau et de maintenance. Pour cela, il faut d’abord définir le besoin, puis choisir une architecture simple avec alimentation adaptée, réseau local et traitement des données, avant de vérifier si la solution reste durable et réaliste.',
    fiveMinutes: 'Je commence par le besoin: dans certaines zones, le réseau n’est pas stable et l’énergie est limitée. Une infrastructure autonome doit donc fonctionner localement, avec une consommation maîtrisée et une maintenance simple. Ensuite, je dimensionne la solution: calcul de l’énergie disponible, estimation de la puissance consommée, choix d’un stockage ou d’un apport solaire, puis organisation du réseau local pour transmettre les données utiles. Enfin, je vérifie la cohérence globale: coût, robustesse, réparabilité, sécurité et impact environnemental. Le but n’est pas d’avoir la solution la plus sophistiquée, mais celle qui répond vraiment au terrain.',
    jury: [
      {
        q: 'Pourquoi avoir choisi une solution autonome plutôt qu’un système relié à un réseau central ?',
        a: 'Parce que la contrainte principale est justement l’accès irrégulier à l’énergie et au réseau. L’autonomie rend le service plus fiable.',
      },
      {
        q: 'Quelles grandeurs scientifiques pouvez-vous utiliser ?',
        a: 'La puissance, l’énergie, la durée d’utilisation, les rendements et les ordres de grandeur pour vérifier la cohérence.',
      },
      {
        q: 'Comment relier ce sujet au développement durable ?',
        a: 'En travaillant la sobriété énergétique, la durabilité, la maintenance simple et l’utilité sociale de la solution.',
      },
      {
        q: 'Quel est le principal risque technique ?',
        a: 'Sous-dimensionner l’énergie ou la connectivité, ce qui rendrait le système inutilisable au quotidien.',
      },
    ],
  },
  {
    id: 'or-drone',
    title: 'L’optimisation d’un système de drone pour les recherches de personnes en zone critique dans la gendarmerie',
    problem: 'Comment optimiser un drone pour rechercher des personnes rapidement et efficacement dans une zone critique, tout en respectant les contraintes de sécurité et d’autonomie ?',
    intro: 'Ce sujet met en valeur la chaîne d’information, les capteurs, l’autonomie énergétique, la communication et les contraintes d’un système embarqué.',
    plan: [
      '1. Définir la mission: repérer, transmettre et alerter dans une zone dangereuse.',
      '2. Optimiser le drone: autonomie, capteurs, portée, robustesse et traitement des données.',
      '3. Vérifier les limites: sécurité, coût, réglementation, fiabilité et impact opérationnel.',
    ],
    sti2d: ['Systèmes embarqués', 'Capteurs', 'Actionneurs', 'Chaînes d’information', 'Contraintes techniques'],
    sciences: ['Énergie', 'Puissance', 'Rendement', 'Ordres de grandeur', 'Mesures'],
    impacts: [
      'Société: améliorer les opérations de recherche et réduire le risque pour les secouristes.',
      'Développement durable: mieux utiliser l’énergie et limiter les moyens lourds inutiles.',
      'Contraintes réelles: autonomie, météo, visibilité, portée radio, réglementation et sécurité.',
    ],
    conclusion: 'Optimiser un drone, ce n’est pas seulement l’équiper de meilleurs composants, c’est trouver le meilleur compromis entre efficacité, sécurité et autonomie.',
    opening: 'On peut ouvrir sur l’usage d’autres systèmes autonomes dans les secours, la surveillance ou la cartographie.',
    memo: [
      'Parler de la mission avant de parler des composants.',
      'Citer la chaîne d’information et la chaîne d’énergie.',
      'Montrer le compromis entre autonomie et performance.',
      'Rester concret avec un cas d’usage gendarmerie.',
    ],
    twoMinutes: 'Je présente un drone utilisé pour rechercher des personnes en zone critique. Le problème est de repérer vite une victime, transmettre les informations et rester suffisamment autonome pour intervenir. Pour cela, il faut optimiser les capteurs, la communication, l’autonomie énergétique et la robustesse du système. Mon objectif est de montrer le compromis entre efficacité opérationnelle et contraintes de terrain.',
    fiveMinutes: 'Je commence par la mission: dans une zone critique, il faut observer rapidement, localiser une personne et transmettre l’information à distance. Le drone doit donc intégrer une chaîne d’information performante avec capteurs adaptés, traitement rapide et communication fiable. Il doit aussi posséder une chaîne d’énergie bien dimensionnée pour assurer assez d’autonomie sans alourdir l’appareil. Enfin, l’optimisation passe par des choix réalistes: poids, coût, sécurité, météo, réglementation et facilité de déploiement. Le plus important est de garder une solution efficace sur le terrain, pas seulement séduisante sur le papier.',
    jury: [
      {
        q: 'Pourquoi les capteurs sont-ils essentiels ?',
        a: 'Parce qu’ils permettent de détecter, repérer ou confirmer la présence d’une personne et d’envoyer une information exploitable.',
      },
      {
        q: 'Quelle est la principale contrainte technique ?',
        a: 'L’autonomie, car le drone doit rester léger tout en embarquant suffisamment d’énergie et de fonctionnalités.',
      },
      {
        q: 'Comment parler du développement durable sur ce sujet ?',
        a: 'En montrant qu’une meilleure optimisation limite les moyens déployés, réduit les consommations et améliore l’efficacité globale.',
      },
      {
        q: 'Quel compromis technique peut être discuté ?',
        a: 'Plus de capteurs et plus de traitement améliorent la recherche, mais augmentent le poids, la consommation et parfois le coût.',
      },
    ],
  },
];

export const oralTraining = [
  { date: '2026-06-16', goal: 'Choisir le sujet, relire la problématique et dire le plan sans notes' },
  { date: '2026-06-17', goal: 'Raconter l’introduction de façon claire en 2 minutes' },
  { date: '2026-06-18', goal: 'Faire une version longue du sujet 1 avec chrono' },
  { date: '2026-06-19', goal: 'Répondre à 5 questions possibles du jury' },
  { date: '2026-06-20', goal: 'Travailler la posture, la voix et les transitions' },
  { date: '2026-06-21', goal: 'Faire une répétition complète du sujet 2' },
  { date: '2026-06-22', goal: 'Identifier les passages trop compliqués et simplifier le vocabulaire' },
  { date: '2026-06-23', goal: 'Entraînement debout avec fiche mémo uniquement' },
  { date: '2026-06-24', goal: 'Répondre sans hésiter aux questions de société et de technique' },
  { date: '2026-06-25', goal: 'Repasser le sujet 1 en version 2 minutes' },
  { date: '2026-06-26', goal: 'Repasser le sujet 2 en version 2 minutes' },
  { date: '2026-06-27', goal: 'Simulation de jury avec pause et respiration' },
  { date: '2026-06-28', goal: 'Relire les fiches mémo et réduire le texte au strict nécessaire' },
  { date: '2026-06-29', goal: 'Dernière répétition légère, coucher tôt, préparer le matériel' },
  { date: '2026-06-30', goal: 'Grand Oral: se présenter calmement, parler lentement, conclure nettement' },
];

export const tests = [
  {
    id: 'test-1',
    title: 'Mini-test 1 - Bases',
    focus: 'Calculs, unités et lecture simple',
    questions: [
      {
        prompt: 'Combien vaut 20 % de 150 ?',
        choices: ['20', '25', '30', '35'],
        answer: 2,
        correction: '20 % de 150 = 0,2 × 150 = 30.',
      },
      {
        prompt: 'Quelle est l’unité de la tension électrique ?',
        choices: ['A', 'V', 'Ω', 'W'],
        answer: 1,
        correction: 'La tension se mesure en volts, notés V.',
      },
      {
        prompt: 'Si f(x) = 2x + 1, combien vaut f(3) ?',
        choices: ['5', '6', '7', '8'],
        answer: 2,
        correction: 'f(3) = 2 × 3 + 1 = 7.',
      },
    ],
  },
  {
    id: 'test-2',
    title: 'Mini-test 2 - Physique',
    focus: 'Énergie, puissance et loi d’Ohm',
    questions: [
      {
        prompt: 'Quelle formule relie tension, résistance et intensité ?',
        choices: ['U = R × I', 'P = E × t', 'E = R / I', 'I = U × t'],
        answer: 0,
        correction: 'La loi d’Ohm s’écrit U = R × I.',
      },
      {
        prompt: 'Une puissance de 2 kW vaut :',
        choices: ['20 W', '200 W', '2000 W', '20000 W'],
        answer: 2,
        correction: 'kilo signifie 10^3, donc 2 kW = 2000 W.',
      },
      {
        prompt: 'Le rendement compare surtout :',
        choices: ['La longueur et le temps', 'L’utile et le reçu', 'La masse et le volume', 'La tension et l’intensité'],
        answer: 1,
        correction: 'Le rendement est un rapport entre ce qui est utile et ce qui est reçu.',
      },
    ],
  },
  {
    id: 'test-3',
    title: 'Mini-test 3 - STI2D',
    focus: 'Chaînes fonctionnelles et contraintes',
    questions: [
      {
        prompt: 'La chaîne d’information sert à :',
        choices: ['Produire l’énergie', 'Traiter et transmettre une information', 'Stocker la matière', 'Augmenter la masse'],
        answer: 1,
        correction: 'La chaîne d’information capte, traite et transmet des informations.',
      },
      {
        prompt: 'Un capteur transforme :',
        choices: ['Une décision en énergie', 'Une grandeur physique en information', 'Une batterie en moteur', 'Un signal en matière'],
        answer: 1,
        correction: 'Un capteur mesure une grandeur physique et la transforme en information.',
      },
      {
        prompt: 'Une contrainte technique peut être :',
        choices: ['Le goût de l’utilisateur', 'Le poids maximum', 'Le hasard', 'Le nombre de pages du sujet'],
        answer: 1,
        correction: 'Le poids maximum est une vraie contrainte de conception.',
      },
    ],
  },
  {
    id: 'test-4',
    title: 'Mini-test 4 - Grand Oral',
    focus: 'Argumentation et vocabulaire',
    questions: [
      {
        prompt: 'Pour un Grand Oral, le plus important est :',
        choices: ['Réciter vite', 'Parler sans respirer', 'Répondre clairement à la problématique', 'Dire beaucoup de mots techniques'],
        answer: 2,
        correction: 'Le jury attend une réponse claire, structurée et maîtrisée.',
      },
      {
        prompt: 'Une bonne introduction doit :',
        choices: ['Partir du sujet puis annoncer le plan', 'Commencer par des détails complexes', 'Oublier la problématique', 'Terminer sans conclusion'],
        answer: 0,
        correction: 'L’introduction doit amener le sujet, poser la problématique et annoncer le plan.',
      },
      {
        prompt: 'Si le score est faible, il faut surtout :',
        choices: ['Tout arrêter', 'Revoir les erreurs et simplifier', 'Changer de sujet au hasard', 'Apprendre sans comprendre'],
        answer: 1,
        correction: 'Le plus efficace est de corriger les erreurs et de simplifier le discours.',
      },
    ],
  },
];

export const methodAdvice = [
  {
    title: 'Réviser quand on est en difficulté',
    body: 'Ne cherche pas à tout revoir d’un coup. Prends une seule notion, une fiche courte et 3 exercices maximum. Le but est de reprendre confiance avec des réussites rapides.',
  },
  {
    title: 'Faire une fiche utile',
    body: 'Une fiche utile tient sur une page, avec des mots simples, une formule, un exemple et 3 erreurs à éviter. Si c’est trop long, ce n’est plus une fiche.',
  },
  {
    title: 'Faire un exercice correctement',
    body: 'Lis la question, note les données, choisis la formule, calcule proprement puis écris une phrase de conclusion. En cas d’erreur, recommence en expliquant chaque étape.',
  },
  {
    title: 'Corriger ses erreurs',
    body: 'Ne te contente pas de regarder la correction. Réécris l’exercice sans aide et note pourquoi tu t’es trompé. Une erreur non expliquée revient souvent.',
  },
  {
    title: 'Réviser la dernière semaine',
    body: 'La dernière semaine doit servir à consolider, pas à découvrir. Revois les fiches essentielles, les formules, les erreurs fréquentes et le matériel du bac.',
  },
  {
    title: 'Gérer le stress',
    body: 'Respire, dors assez et garde une routine simple. Le stress baisse quand tu sais exactement quoi faire: une fiche, un exercice, une pause.',
  },
  {
    title: 'Préparer un oral',
    body: 'Parle lentement, annonce ton plan, regarde le jury et fais des phrases courtes. Répète à voix haute avec chrono pour éviter de te perdre.',
  },
  {
    title: 'Ne pas se décourager',
    body: 'L’objectif n’est pas la perfection. L’objectif est de gagner des points sur les chapitres rentables et de sécuriser les bases. Chaque séance compte.',
  },
];

export const bacPractice = [
  {
    id: 'bac-maths-1',
    subject: 'Mathématiques',
    title: 'Sujet type bac - Analyse de données techniques',
    context: 'Un capteur de température d’un local informatique envoie plusieurs mesures sur une journée.',
    questions: [
      'Lire une valeur sur un graphique et préciser son unité.',
      'Calculer une variation en pourcentage entre deux mesures.',
      'Interpréter la tendance et conclure sur la stabilité du système.',
    ],
    correction: [
      'Étape 1: lire les axes, l’échelle et l’unité avant toute réponse.',
      'Étape 2: calculer la variation avec une écriture claire puis vérifier si le résultat est logique.',
      'Étape 3: conclure sur la tendance en reliant directement le chiffre au système technique.',
    ],
    commonMistakes: [
      'Donner une valeur sans unité.',
      'Confondre valeur lue et interprétation.',
      'Oublier de dire si la situation est stable ou non.',
    ],
  },
  {
    id: 'bac-pc-1',
    subject: 'Physique-chimie',
    title: 'Sujet type bac - Alimentation d’un système',
    context: 'Une solution technique fonctionne sur batterie et alimente un moteur et une carte électronique.',
    questions: [
      'Calculer la puissance électrique consommée par un composant.',
      'Utiliser U = R x I pour trouver la grandeur inconnue.',
      'Estimer l’énergie consommée sur une durée d’utilisation.',
    ],
    correction: [
      'Étape 1: relever les données utiles et convertir les unités avant le calcul.',
      'Étape 2: choisir la formule adaptée, isoler la grandeur cherchée et écrire le calcul proprement.',
      'Étape 3: vérifier la cohérence du résultat puis relier la puissance à l’autonomie du système.',
    ],
    commonMistakes: [
      'Choisir la formule au hasard.',
      'Oublier la conversion des unités.',
      'Rendre un résultat sans interprétation dans le contexte.',
    ],
  },
  {
    id: 'bac-sti2d-1',
    subject: 'STI2D / SIN',
    title: 'Sujet type bac - Drone de recherche',
    context: 'Un drone doit repérer une personne, transmettre l’information et rester autonome.',
    questions: [
      'Identifier la chaîne d’information et la chaîne d’énergie.',
      'Justifier le choix d’un capteur et d’un actionneur.',
      'Expliquer une contrainte de sécurité, d’autonomie ou de coût.',
    ],
    correction: [
      'Étape 1: séparer clairement la chaîne d’information de la chaîne d’énergie.',
      'Étape 2: associer chaque capteur et actionneur à son rôle précis dans la mission.',
      'Étape 3: terminer en expliquant le compromis entre performance, autonomie et contraintes de terrain.',
    ],
    commonMistakes: [
      'Mélanger information et énergie.',
      'Parler de composants sans expliquer leur rôle.',
      'Oublier la contrainte principale du système.',
    ],
  },
];

export const priorityCards = [
  {
    subject: 'Mathématiques',
    title: 'Ultra-prioritaire',
    items: [
      'Calculs de base et automatismes',
      'Pourcentages, proportionnalité et puissances',
      'Lecture de graphiques',
      'Fonctions et dérivation simple',
      'Probabilités et statistiques de base',
    ],
    method: [
      'Faire 15 minutes de calculs par jour.',
      'Toujours écrire les unités et la conclusion.',
      'Refaire les erreurs sans regarder la correction immédiatement.',
    ],
  },
  {
    subject: 'Physique-chimie',
    title: 'Ultra-prioritaire',
    items: [
      'Grandeurs et unités',
      'Conversions',
      'Énergie, puissance et rendement',
      'Électricité, loi d’Ohm et puissance électrique',
      'Graphiques, mesures et ordres de grandeur',
    ],
    method: [
      'Apprendre les formules utiles par cœur.',
      'Toujours convertir avant de calculer.',
      'Vérifier si le résultat est cohérent avec la situation.',
    ],
  },
  {
    subject: 'STI2D / SIN',
    title: 'Ultra-prioritaire',
    items: [
      'Chaîne d’information',
      'Chaîne d’énergie',
      'Capteurs et actionneurs',
      'Systèmes embarqués et réseaux',
      'Analyse fonctionnelle et contraintes techniques',
    ],
    method: [
      'S’entraîner à décrire un système en 4 blocs.',
      'Toujours faire le lien entre besoin réel et solution technique.',
      'Utiliser le vocabulaire exact sans faire des phrases trop longues.',
    ],
  },
];

export const priorityChecklist = [
  {
    day: 'Lundi matin',
    subject: 'Mathématiques',
    title: 'Remise en route',
    tasks: [
      '10 min de calculs de base',
      '10 min sur les pourcentages ou les puissances',
      '10 min de correction active',
    ],
  },
  {
    day: 'Mardi matin',
    subject: 'Physique-chimie',
    title: 'Unités et formules',
    tasks: [
      '10 min de conversions',
      '10 min de formule énergie, puissance ou Ohm',
      '10 min de vérification de résultat',
    ],
  },
  {
    day: 'Mercredi matin',
    subject: 'STI2D / SIN',
    title: 'Chaînes et système',
    tasks: [
      '10 min de vocabulaire technique',
      '10 min de schéma chaîne d’information ou d’énergie',
      '10 min de phrase de conclusion',
    ],
  },
  {
    day: 'Jeudi matin',
    subject: 'Mathématiques',
    title: 'Graphiques et variations',
    tasks: [
      '10 min de lecture de graphique',
      '10 min de dérivation ou de suites',
      '10 min de réponse rédigée',
    ],
  },
  {
    day: 'Vendredi matin',
    subject: 'Physique-chimie',
    title: 'Mesures et interprétation',
    tasks: [
      '10 min sur grandeurs et unités',
      '10 min sur un exercice court',
      '10 min pour corriger ce qui bloque',
    ],
  },
  {
    day: 'Samedi matin',
    subject: 'Mix',
    title: 'Consolidation',
    tasks: [
      '10 min de rappel maths',
      '10 min de rappel physique-chimie',
      '10 min de rappel STI2D',
    ],
  },
  {
    day: 'Dimanche matin',
    subject: 'Léger',
    title: 'Relecture calme',
    tasks: [
      '10 min de relecture des fiches',
      '10 min de flashcards ou de récitation',
      '10 min pour préparer la semaine suivante',
    ],
  },
];

export const quickRevision = [
  {
    id: 'qr-maths',
    subject: 'Mathématiques',
    title: '30 minutes chrono - Maths',
    blocks: [
      '5 min: relire une mini-fiche ou la formule du jour.',
      '15 min: faire un exercice très court sans s’arrêter.',
      '10 min: corriger et écrire l’erreur à éviter.',
    ],
  },
  {
    id: 'qr-pc',
    subject: 'Physique-chimie',
    title: '30 minutes chrono - Physique-chimie',
    blocks: [
      '5 min: noter les unités et la formule à utiliser.',
      '15 min: faire un calcul complet avec conversion.',
      '10 min: vérifier le résultat et la cohérence physique.',
    ],
  },
  {
    id: 'qr-sti2d',
    subject: 'STI2D / SIN',
    title: '30 minutes chrono - STI2D',
    blocks: [
      '5 min: revoir le vocabulaire de système.',
      '15 min: décrire un objet technique en chaîne d’information/énergie.',
      '10 min: écrire une conclusion claire et courte.',
    ],
  },
];

export const frequentErrors = [
  {
    subject: 'Mathématiques',
    errors: [
      {
        title: 'Oublier les unités ou le contexte',
        fix: 'Écrire l’unité à chaque ligne de calcul et relire la question avant la conclusion.',
      },
      {
        title: 'Aller trop vite dans les calculs',
        fix: 'Poser chaque étape et vérifier à la fin avec une estimation simple.',
      },
      {
        title: 'Confondre variation et valeur',
        fix: 'Dire clairement ce qui est lu, puis ce que ça veut dire.',
      },
      {
        title: 'Mal interpréter un graphique',
        fix: 'Regarder l’échelle, les axes et la légende avant de répondre.',
      },
    ],
  },
  {
    subject: 'Physique-chimie',
    errors: [
      {
        title: 'Utiliser une mauvaise formule',
        fix: 'Identifier la grandeur cherchée avant de choisir la relation.',
      },
      {
        title: 'Oublier les conversions',
        fix: 'Convertir en unités de base avant le calcul principal.',
      },
      {
        title: 'Mélanger puissance et énergie',
        fix: 'Se rappeler que la puissance est liée à la rapidité, l’énergie à la quantité totale.',
      },
      {
        title: 'Répondre sans conclusion',
        fix: 'Terminer par une phrase qui reformule le résultat dans le contexte.',
      },
    ],
  },
  {
    subject: 'STI2D / SIN',
    errors: [
      {
        title: 'Confondre chaîne d’information et chaîne d’énergie',
        fix: 'La chaîne d’information traite et décide; la chaîne d’énergie alimente et agit.',
      },
      {
        title: 'Rester trop vague',
        fix: 'Nommer les blocs, les rôles et le besoin réel du système.',
      },
      {
        title: 'Oublier les contraintes',
        fix: 'Citer au moins une contrainte de coût, d’autonomie, de sécurité ou de maintenance.',
      },
      {
        title: 'Parler de la solution sans parler du problème',
        fix: 'Commencer par le besoin puis montrer comment la technique y répond.',
      },
    ],
  },
];
